export const errorCard = {
  adult: false,
  backdrop_path: "",
  genre_ids: [0],
  id: 0,
  original_language: "",
  original_title: "Failed to Fetch Title",
  overview: "",
  popularity: 0,
  poster_path: "",
  release_date: "",
  title: "Failed to Fetch Title",
  video: false,
  vote_average: 0,
  vote_count: 0,
};
