import { Movie, MovieApiResponse } from "../types/movie_types";

export const errorCard: Movie = {
  adult: false,
  backdrop_path: "/",
  genre_ids: [0],
  id: 1,
  original_language: "eng-us",
  original_title: "Failed to Fetch Title",
  overview: "null",
  popularity: 0,
  poster_path: "/",
  release_date: "00-00-0000",
  title: "null",
  video: false,
  vote_average: 0,
  vote_count: 0,
};

// Sample for MSW --- The Batman, ID: 414906
export const noMatchingMovieIdPage1: MovieApiResponse = {
  page: 1,
  results: [
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
  ],
  total_pages: 4,
  total_results: 61,
};
export const noMatchingMovieIdPage2: MovieApiResponse = {
  page: 2,
  results: [
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
  ],
  total_pages: 4,
  total_results: 61,
};
export const noMatchingMovieIdPage3: MovieApiResponse = {
  page: 3,
  results: [
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
    errorCard,
  ],
  total_pages: 4,
  total_results: 61,
};
export const noMatchingMovieIdPage4: MovieApiResponse = {
  page: 4,
  results: [
    errorCard,
    {
      adult: false,
      backdrop_path: "",
      genre_ids: [0],
      id: 414906,
      original_language: "",
      original_title: "THE BATMAN",
      overview: "",
      popularity: 0,
      poster_path: "",
      release_date: "",
      title: "THE BATMAN",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    errorCard,
    errorCard,
  ],
  total_pages: 4,
  total_results: 61,
};
